#!/bin/bash

# Check if you are on the "main" branch
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ]; then
    echo "Successful commit on the 'main' branch!"
else
    echo "Commit made on the '$BRANCH' branch!"
fi
