#!/bin/bash

# Verifica si estás en la rama "main"
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ]; then
    echo "¡Commit exitoso en la rama 'main'!"
else
    echo "¡Commit realizado en la rama '$BRANCH'!"
fi
